---
- name: Setting up MTU size 
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-{{interface_name}} line="MTU={{mtu_size}}"
  register: mtu_size

- name: Starting network service
  service: name=network state=restarted enabled=yes
  when: "mtu_size.changed == True"
