---
- name: Setting up timezone
  command: timedatectl set-timezone {{timezone}}

- name: Setting up hostname
  hostname: name="{{inventory_hostname}}"

- name: Setting up resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: Updating Hosts file
  template: src={{project}}.hosts dest=/etc/hosts mode=0644  

- name: Installing EPEL  Packages
  package: name="{{epel_package}}" state=present

- name: Installing Packages
  package: name="{{item}}" state=present
  with_items: 
  - "{{package_list}}"

